import matplotlib.pyplot as plt
from matplotlib.widgets import RadioButtons, Button # Import Button widget
from matplotlib.animation import FuncAnimation
import numpy as np
import os
from collections import deque
import tkinter as tk
from tkinter import filedialog
import threading
import queue
import sys

# --- Global state variables ---
USER_SELECTED_INTERVAL_MS = 20 # Default plotting speed
selected_directory = ""
g_animation = None
g_all_raw_weights = np.array([])
g_all_filtered_weights = np.array([])
g_simulation_running = False

# Global variables to store the currently plotted data and its metadata
g_current_file_name = ""
g_current_analysis_text = ""

PLOT_WINDOW_SIZE = 500

# Configuration (used for plot title, but filtering is done by C program)
FIR_CUTOFF_HZ = 10.0 # This is now just for display in the plot title

# Global variables for plotting (managed by init_plot)
current_fig, current_axes = None, None
current_raw_line, current_filtered_line = None, None
speed_radio_buttons = None
pause_button = None # Global reference for Pause button
resume_button = None # Global reference for Resume button


def load_and_process_file_worker(original_filepath, data_queue):
    """
    Worker thread function: Reads the CSV files (raw and filtered) generated by the C program
    and puts the data into a queue for the main thread to plot.
    """
    print(f"[APP] Loading processed data for: {original_filepath}")

    output_data_dir = "output_data"
    analysis_results_dir = "analysis_results"

    # Derive the CSV and analysis file names from the original .txt filename
    base_filename_txt = os.path.basename(original_filepath)
    # Ensure the base_filename_txt ends with .txt for replacement logic
    if not base_filename_txt.endswith('.txt'):
        base_filename_txt = base_filename_txt + '.txt'

    raw_csv_filename = f"raw_weights_{base_filename_txt.replace('.txt', '.csv')}"
    filtered_csv_filename = f"filtered_weights_{base_filename_txt.replace('.txt', '.csv')}"
    analysis_txt_filename = f"analysis_{base_filename_txt}"

    raw_filepath_csv = os.path.join(output_data_dir, raw_csv_filename)
    filtered_filepath_csv = os.path.join(output_data_dir, filtered_csv_filename)
    analysis_filepath = os.path.join(analysis_results_dir, analysis_txt_filename)

    raw_data = []
    filtered_data = []
    analysis_text = ""

    try:
        # Read raw data from CSV
        with open(raw_filepath_csv, 'r') as f:
            for line in f:
                try:
                    raw_data.append(float(line.strip()))
                except ValueError:
                    continue # Skip invalid lines
        raw_data = np.array(raw_data)
        print(f"Loaded raw data from: {raw_filepath_csv}")

        # Read filtered data from CSV
        with open(filtered_filepath_csv, 'r') as f:
            for line in f:
                try:
                    filtered_data.append(float(line.strip()))
                except ValueError:
                    continue # Skip invalid lines
        filtered_data = np.array(filtered_data)
        print(f"Loaded filtered data from: {filtered_filepath_csv}")

        # Read analysis results
        if os.path.exists(analysis_filepath):
            with open(analysis_filepath, 'r') as f:
                analysis_text = f.read()
            print(f"Loaded analysis results from: {analysis_filepath}")
        else:
            print(f"Analysis file not found: {analysis_filepath}")

        # Put the loaded data into the queue for the main thread
        data_queue.put((raw_data, filtered_data, original_filepath, analysis_text))

    except FileNotFoundError as e:
        print(f"Error: Required data file(s) not found. Ensure the C program has been run for '{base_filename_txt}'. {e}")
        data_queue.put(None) # Signal error
    except Exception as e:
        print(f"An unexpected error occurred during data loading: {e}")
        data_queue.put(None) # Signal error


def init_plot():
    """Initializes the Matplotlib figure and all interactive widgets."""
    global current_fig, current_axes, current_raw_line, current_filtered_line, speed_radio_buttons
    global pause_button, resume_button # Access new global button references

    plt.close('all') # Close any existing figures
    current_fig, current_axes = plt.subplots(2, 1, figsize=(12, 7))
    plt.subplots_adjust(left=0.25, bottom=0.1, right=0.95, top=0.95) # Adjusted left margin for widgets

    # Initial empty plot lines, animated=True is key for FuncAnimation
    current_raw_line, = current_axes[0].plot([], [], 'r-', label="Raw Data", animated=True)
    current_filtered_line, = current_axes[1].plot([], [], 'k-', label=f"FIR-Filtered Data", animated=True)
    
    for ax in current_axes:
        ax.grid(True)
        ax.legend(loc='upper right')
        ax.set_xlim(0, PLOT_WINDOW_SIZE)
        ax.set_ylim(-1, 1) # Default Y-limits, will be adjusted later

    current_axes[0].set_title("Live Plotting Data") # Generic title
    current_axes[0].set_ylabel("Weight")
    current_axes[1].set_title("Filtered Data")
    current_axes[1].set_xlabel("Sample Index")
    current_axes[1].set_ylabel("Weight")
    
    # Speed Control Widget
    current_fig.text(0.02, 0.9, "Plotting Speed", fontsize=10, weight='bold')
    speed_widget_ax = plt.axes([0.02, 0.65, 0.15, 0.25]) # Adjusted size and position
    speed_options = ["1ms", "2ms", "5ms", "10ms", "20ms", "50ms", "100ms"]
    speed_radio_buttons = RadioButtons(speed_widget_ax, speed_options, active=speed_options.index(f"{USER_SELECTED_INTERVAL_MS}ms"))
    
    def on_speed_change(label):
        global USER_SELECTED_INTERVAL_MS, g_animation, g_simulation_running
        global g_all_raw_weights, g_all_filtered_weights, g_current_file_name, g_current_analysis_text

        new_interval = int(label.replace('ms', ''))
        if new_interval == USER_SELECTED_INTERVAL_MS:
            print(f"[APP] Speed already set to: {USER_SELECTED_INTERVAL_MS}ms. No change needed.")
            return

        USER_SELECTED_INTERVAL_MS = new_interval
        print(f"[APP] Attempting to change speed to: {USER_SELECTED_INTERVAL_MS}ms interval.")

        if g_simulation_running and g_all_raw_weights.size > 0: # Check if an animation is active and has data
            # Stop current animation (if it exists and is running)
            if g_animation and g_animation.event_source:
                g_animation.event_source.stop()
                g_animation = None # Clear reference to old animation
                g_simulation_running = False # Mark as stopped temporarily
                print("[APP] Previous animation stopped for speed change.")

            # Restart animation with the new interval using the globally stored data
            # This will cause the plot to restart from the beginning, but ensures speed change.
            start_new_animation(g_all_raw_weights, g_all_filtered_weights, g_current_file_name, g_current_analysis_text)
            print(f"[APP] Animation restarted with new speed: {USER_SELECTED_INTERVAL_MS}ms.")
        else:
            print(f"[APP] Speed set to: {USER_SELECTED_INTERVAL_MS}ms. Animation will start with this speed when data is loaded.")

    speed_radio_buttons.on_clicked(on_speed_change)

    # Pause/Resume Buttons
    # Position them below the speed radio buttons
    pause_ax = plt.axes([0.02, 0.55, 0.15, 0.05]) # x, y, width, height
    resume_ax = plt.axes([0.02, 0.48, 0.15, 0.05])

    pause_button = Button(pause_ax, 'Pause')
    resume_button = Button(resume_ax, 'Resume')

    def on_pause(event):
        global g_animation
        if g_animation and g_animation.event_source:
            g_animation.event_source.stop()
            print("[APP] Animation Paused.")

    def on_resume(event):
        global g_animation
        if g_animation and g_animation.event_source:
            g_animation.event_source.start()
            print("[APP] Animation Resumed.")

    pause_button.on_clicked(on_pause)
    resume_button.on_clicked(on_resume)
    
    return current_fig


def update_animation_frame(frame):
    """Function called by FuncAnimation for each frame."""
    global g_all_raw_weights, g_all_filtered_weights

    # Update the lines with data up to the current frame
    x_data = np.arange(frame + 1)
    y_raw = g_all_raw_weights[:frame + 1]
    y_filtered = g_all_filtered_weights[:frame + 1]

    current_raw_line.set_data(x_data, y_raw)
    current_filtered_line.set_data(x_data, y_filtered)
    
    # Determine the dynamic x-axis limits
    total_data_length = len(g_all_raw_weights)
    current_frame_index = frame

    if total_data_length <= PLOT_WINDOW_SIZE:
        x_min = 0
        x_max = total_data_length + total_data_length * 0.05
        if x_max < PLOT_WINDOW_SIZE:
            x_max = PLOT_WINDOW_SIZE
    else:
        x_min = max(0, current_frame_index + 1 - PLOT_WINDOW_SIZE)
        x_max = x_min + PLOT_WINDOW_SIZE

    current_axes[0].set_xlim(x_min, x_max)
    current_axes[1].set_xlim(x_min, x_max)

    # Also adjust Y-limits dynamically based on the *currently visible* data
    visible_raw_data = g_all_raw_weights[int(x_min):int(x_max)]
    visible_filtered_data = g_all_filtered_weights[int(x_min):int(x_max)]

    min_y_visible = np.nanmin([np.nanmin(visible_raw_data), np.nanmin(visible_filtered_data)]) if visible_raw_data.size > 0 else -1
    max_y_visible = np.nanmax([np.nanmax(visible_raw_data), np.nanmax(visible_filtered_data)]) if visible_raw_data.size > 0 else 1

    if np.isfinite(min_y_visible) and np.isfinite(max_y_visible):
        padding_y = (max_y_visible - min_y_visible) * 0.1 if (max_y_visible - min_y_visible) > 0 else 0.1
        current_axes[0].set_ylim(min_y_visible - padding_y, max_y_visible + padding_y)
        current_axes[1].set_ylim(min_y_visible - padding_y, max_y_visible + padding_y)
    else:
        current_axes[0].set_ylim(-1, 1)
        current_axes[1].set_ylim(-1, 1)

    return current_raw_line, current_filtered_line


def start_new_animation(all_raw, all_filtered, file_name, analysis_text):
    """Sets up and starts a new animation in the main thread."""
    global g_all_raw_weights, g_all_filtered_weights, g_animation, g_simulation_running
    global g_current_file_name, g_current_analysis_text

    # Store current data and metadata globally for potential re-animation
    g_all_raw_weights = all_raw
    g_all_filtered_weights = all_filtered
    g_current_file_name = file_name
    g_current_analysis_text = analysis_text
    
    base_name = os.path.basename(file_name)
    current_axes[0].set_title(f"Raw ADC Data - {base_name}")
    current_axes[1].set_title(f"FIR-Filtered Data - {base_name}")
    
    # Reset plot limits based on the new data
    current_axes[0].set_xlim(0, PLOT_WINDOW_SIZE)
    current_axes[1].set_xlim(0, PLOT_WINDOW_SIZE)


    # Adjust Y-limits dynamically based on overall data for initial view
    if g_all_raw_weights.size > 0 and np.any(np.isfinite(g_all_raw_weights)):
        min_y_raw, max_y_raw = np.nanmin(g_all_raw_weights), np.nanmax(g_all_raw_weights)
        padding_raw = (max_y_raw - min_y_raw) * 0.1 if (max_y_raw - min_y_raw) > 0 else 1
        current_axes[0].set_ylim(min_y_raw - padding_raw, max_y_raw + padding_raw)
        
    if g_all_filtered_weights.size > 0 and np.any(np.isfinite(g_all_filtered_weights)):
        min_y_filtered, max_y_filtered = np.nanmin(g_all_filtered_weights), np.nanmax(g_all_filtered_weights)
        padding_filtered = (max_y_filtered - min_y_filtered) * 0.1 if (max_y_filtered - min_y_filtered) > 0 else 1
        current_axes[1].set_ylim(min_y_filtered - padding_filtered, max_y_filtered + padding_filtered)


    # Remove previous text annotation if it exists
    for text_obj in current_fig.texts:
        if text_obj.get_text().startswith("Analysis for file:"):
            text_obj.remove()
    
    # Display analysis text as annotation (optional, can be adjusted)
    if analysis_text:
        current_fig.text(0.02, 0.02, analysis_text, fontsize=9, ha='left', va='bottom',
                         bbox=dict(boxstyle="round,pad=0.5", fc="yellow", alpha=0.5))

    # If an animation already exists, stop it before creating a new one
    if g_animation:
        g_animation.event_source.stop()
        g_animation = None

    # Create and start the new animation with the current USER_SELECTED_INTERVAL_MS
    g_animation = FuncAnimation(
        current_fig, 
        update_animation_frame, 
        frames=len(g_all_raw_weights),
        interval=USER_SELECTED_INTERVAL_MS, 
        blit=True, 
        repeat=False
    )
    current_fig.canvas.draw()
    g_simulation_running = True


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python new_plot.py <base_filename.txt>")
        print("Example: python new_plot.py 535g20250502pm427ms20hz50.txt")
        sys.exit(1)
    
    base_filename_from_arg = sys.argv[1]

    root = tk.Tk()
    root.withdraw()

    data_for_plotting_queue = queue.Queue()

    fig = init_plot()
    
    timer = fig.canvas.new_timer(interval=100)
    
    def check_queue():
        global g_simulation_running
        try:
            plot_data = data_for_plotting_queue.get_nowait()
            
            if plot_data:
                all_raw, all_filtered, file_name, analysis_text = plot_data
                start_new_animation(all_raw, all_filtered, file_name, analysis_text)
            else:
                g_simulation_running = False
                print("[APP] Data processing for this file failed or completed. Ready for next plot.")
        except queue.Empty:
            pass
            
        if plt.fignum_exists(fig.number):
            timer.start()
        else:
            print("[APP] Figure closed. Stopping queue check.")

    timer.add_callback(check_queue)
    timer.start()

    print(f"[APP] Live Plotter ready. Loading data for: {base_filename_from_arg}")
    load_and_process_file_worker(base_filename_from_arg, data_for_plotting_queue)
    
    plt.show()

    print("[APP] Application exited.")
